FROM node:14.4.0-alpine as build

RUN apk update \
    && apk upgrade \
    && apk --no-cache add gcc make libc-dev

COPY . /app
WORKDIR /app

RUN make frontend.build

FROM nginx:stable-alpine as production

COPY --from=build /app/static /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]